# Add your code below

version: "3.1"

services:
  hyper-service:
    container_name: hyper-task-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - hyper-task-manager-network
    depends_on:
      - 'mongodb'

    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_HOST_NAME: mongodb
        MONGO_PORT_NUMBER: 27017
        MONGO_PORT_NUBMER: 27017
    env_file:
      - '.env'

  mongodb:
    container_name: hyper-mongo
    image: mongo:6.0.8
    ports:
      - '27027:27017'
    networks:
      - hyper-task-manager-network
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
    env_file:
      - '.env'
volumes:
  mongo-data:
networks:
  hyper-task-manager-network:
